/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as DashboardRouteRouteImport } from './routes/dashboard/route'
import { Route as IndexRouteImport } from './routes/index'
import { Route as DashboardIndexRouteImport } from './routes/dashboard/index'
import { Route as DashboardTemplatesRouteImport } from './routes/dashboard/templates'
import { Route as DashboardSelecionarWorkspaceRouteImport } from './routes/dashboard/selecionar-workspace'
import { Route as DashboardRelatorioRouteImport } from './routes/dashboard/relatorio'
import { Route as DashboardPropostasRouteImport } from './routes/dashboard/propostas'
import { Route as DashboardPortfolioRouteImport } from './routes/dashboard/portfolio'
import { Route as DashboardPipelineRouteImport } from './routes/dashboard/pipeline'
import { Route as DashboardLeadsRouteImport } from './routes/dashboard/leads'
import { Route as DashboardImportarRouteImport } from './routes/dashboard/importar'
import { Route as DashboardFollowupsRouteImport } from './routes/dashboard/followups'
import { Route as DashboardConfiguracoesRouteImport } from './routes/dashboard/configuracoes'

const DashboardRouteRoute = DashboardRouteRouteImport.update({
  id: '/dashboard',
  path: '/dashboard',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const DashboardIndexRoute = DashboardIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => DashboardRouteRoute,
} as any)
const DashboardTemplatesRoute = DashboardTemplatesRouteImport.update({
  id: '/templates',
  path: '/templates',
  getParentRoute: () => DashboardRouteRoute,
} as any)
const DashboardSelecionarWorkspaceRoute =
  DashboardSelecionarWorkspaceRouteImport.update({
    id: '/selecionar-workspace',
    path: '/selecionar-workspace',
    getParentRoute: () => DashboardRouteRoute,
  } as any)
const DashboardRelatorioRoute = DashboardRelatorioRouteImport.update({
  id: '/relatorio',
  path: '/relatorio',
  getParentRoute: () => DashboardRouteRoute,
} as any)
const DashboardPropostasRoute = DashboardPropostasRouteImport.update({
  id: '/propostas',
  path: '/propostas',
  getParentRoute: () => DashboardRouteRoute,
} as any)
const DashboardPortfolioRoute = DashboardPortfolioRouteImport.update({
  id: '/portfolio',
  path: '/portfolio',
  getParentRoute: () => DashboardRouteRoute,
} as any)
const DashboardPipelineRoute = DashboardPipelineRouteImport.update({
  id: '/pipeline',
  path: '/pipeline',
  getParentRoute: () => DashboardRouteRoute,
} as any)
const DashboardLeadsRoute = DashboardLeadsRouteImport.update({
  id: '/leads',
  path: '/leads',
  getParentRoute: () => DashboardRouteRoute,
} as any)
const DashboardImportarRoute = DashboardImportarRouteImport.update({
  id: '/importar',
  path: '/importar',
  getParentRoute: () => DashboardRouteRoute,
} as any)
const DashboardFollowupsRoute = DashboardFollowupsRouteImport.update({
  id: '/followups',
  path: '/followups',
  getParentRoute: () => DashboardRouteRoute,
} as any)
const DashboardConfiguracoesRoute = DashboardConfiguracoesRouteImport.update({
  id: '/configuracoes',
  path: '/configuracoes',
  getParentRoute: () => DashboardRouteRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/dashboard': typeof DashboardRouteRouteWithChildren
  '/dashboard/configuracoes': typeof DashboardConfiguracoesRoute
  '/dashboard/followups': typeof DashboardFollowupsRoute
  '/dashboard/importar': typeof DashboardImportarRoute
  '/dashboard/leads': typeof DashboardLeadsRoute
  '/dashboard/pipeline': typeof DashboardPipelineRoute
  '/dashboard/portfolio': typeof DashboardPortfolioRoute
  '/dashboard/propostas': typeof DashboardPropostasRoute
  '/dashboard/relatorio': typeof DashboardRelatorioRoute
  '/dashboard/selecionar-workspace': typeof DashboardSelecionarWorkspaceRoute
  '/dashboard/templates': typeof DashboardTemplatesRoute
  '/dashboard/': typeof DashboardIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/dashboard/configuracoes': typeof DashboardConfiguracoesRoute
  '/dashboard/followups': typeof DashboardFollowupsRoute
  '/dashboard/importar': typeof DashboardImportarRoute
  '/dashboard/leads': typeof DashboardLeadsRoute
  '/dashboard/pipeline': typeof DashboardPipelineRoute
  '/dashboard/portfolio': typeof DashboardPortfolioRoute
  '/dashboard/propostas': typeof DashboardPropostasRoute
  '/dashboard/relatorio': typeof DashboardRelatorioRoute
  '/dashboard/selecionar-workspace': typeof DashboardSelecionarWorkspaceRoute
  '/dashboard/templates': typeof DashboardTemplatesRoute
  '/dashboard': typeof DashboardIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/dashboard': typeof DashboardRouteRouteWithChildren
  '/dashboard/configuracoes': typeof DashboardConfiguracoesRoute
  '/dashboard/followups': typeof DashboardFollowupsRoute
  '/dashboard/importar': typeof DashboardImportarRoute
  '/dashboard/leads': typeof DashboardLeadsRoute
  '/dashboard/pipeline': typeof DashboardPipelineRoute
  '/dashboard/portfolio': typeof DashboardPortfolioRoute
  '/dashboard/propostas': typeof DashboardPropostasRoute
  '/dashboard/relatorio': typeof DashboardRelatorioRoute
  '/dashboard/selecionar-workspace': typeof DashboardSelecionarWorkspaceRoute
  '/dashboard/templates': typeof DashboardTemplatesRoute
  '/dashboard/': typeof DashboardIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/dashboard'
    | '/dashboard/configuracoes'
    | '/dashboard/followups'
    | '/dashboard/importar'
    | '/dashboard/leads'
    | '/dashboard/pipeline'
    | '/dashboard/portfolio'
    | '/dashboard/propostas'
    | '/dashboard/relatorio'
    | '/dashboard/selecionar-workspace'
    | '/dashboard/templates'
    | '/dashboard/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/dashboard/configuracoes'
    | '/dashboard/followups'
    | '/dashboard/importar'
    | '/dashboard/leads'
    | '/dashboard/pipeline'
    | '/dashboard/portfolio'
    | '/dashboard/propostas'
    | '/dashboard/relatorio'
    | '/dashboard/selecionar-workspace'
    | '/dashboard/templates'
    | '/dashboard'
  id:
    | '__root__'
    | '/'
    | '/dashboard'
    | '/dashboard/configuracoes'
    | '/dashboard/followups'
    | '/dashboard/importar'
    | '/dashboard/leads'
    | '/dashboard/pipeline'
    | '/dashboard/portfolio'
    | '/dashboard/propostas'
    | '/dashboard/relatorio'
    | '/dashboard/selecionar-workspace'
    | '/dashboard/templates'
    | '/dashboard/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  DashboardRouteRoute: typeof DashboardRouteRouteWithChildren
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/dashboard': {
      id: '/dashboard'
      path: '/dashboard'
      fullPath: '/dashboard'
      preLoaderRoute: typeof DashboardRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/dashboard/': {
      id: '/dashboard/'
      path: '/'
      fullPath: '/dashboard/'
      preLoaderRoute: typeof DashboardIndexRouteImport
      parentRoute: typeof DashboardRouteRoute
    }
    '/dashboard/templates': {
      id: '/dashboard/templates'
      path: '/templates'
      fullPath: '/dashboard/templates'
      preLoaderRoute: typeof DashboardTemplatesRouteImport
      parentRoute: typeof DashboardRouteRoute
    }
    '/dashboard/selecionar-workspace': {
      id: '/dashboard/selecionar-workspace'
      path: '/selecionar-workspace'
      fullPath: '/dashboard/selecionar-workspace'
      preLoaderRoute: typeof DashboardSelecionarWorkspaceRouteImport
      parentRoute: typeof DashboardRouteRoute
    }
    '/dashboard/relatorio': {
      id: '/dashboard/relatorio'
      path: '/relatorio'
      fullPath: '/dashboard/relatorio'
      preLoaderRoute: typeof DashboardRelatorioRouteImport
      parentRoute: typeof DashboardRouteRoute
    }
    '/dashboard/propostas': {
      id: '/dashboard/propostas'
      path: '/propostas'
      fullPath: '/dashboard/propostas'
      preLoaderRoute: typeof DashboardPropostasRouteImport
      parentRoute: typeof DashboardRouteRoute
    }
    '/dashboard/portfolio': {
      id: '/dashboard/portfolio'
      path: '/portfolio'
      fullPath: '/dashboard/portfolio'
      preLoaderRoute: typeof DashboardPortfolioRouteImport
      parentRoute: typeof DashboardRouteRoute
    }
    '/dashboard/pipeline': {
      id: '/dashboard/pipeline'
      path: '/pipeline'
      fullPath: '/dashboard/pipeline'
      preLoaderRoute: typeof DashboardPipelineRouteImport
      parentRoute: typeof DashboardRouteRoute
    }
    '/dashboard/leads': {
      id: '/dashboard/leads'
      path: '/leads'
      fullPath: '/dashboard/leads'
      preLoaderRoute: typeof DashboardLeadsRouteImport
      parentRoute: typeof DashboardRouteRoute
    }
    '/dashboard/importar': {
      id: '/dashboard/importar'
      path: '/importar'
      fullPath: '/dashboard/importar'
      preLoaderRoute: typeof DashboardImportarRouteImport
      parentRoute: typeof DashboardRouteRoute
    }
    '/dashboard/followups': {
      id: '/dashboard/followups'
      path: '/followups'
      fullPath: '/dashboard/followups'
      preLoaderRoute: typeof DashboardFollowupsRouteImport
      parentRoute: typeof DashboardRouteRoute
    }
    '/dashboard/configuracoes': {
      id: '/dashboard/configuracoes'
      path: '/configuracoes'
      fullPath: '/dashboard/configuracoes'
      preLoaderRoute: typeof DashboardConfiguracoesRouteImport
      parentRoute: typeof DashboardRouteRoute
    }
  }
}

interface DashboardRouteRouteChildren {
  DashboardConfiguracoesRoute: typeof DashboardConfiguracoesRoute
  DashboardFollowupsRoute: typeof DashboardFollowupsRoute
  DashboardImportarRoute: typeof DashboardImportarRoute
  DashboardLeadsRoute: typeof DashboardLeadsRoute
  DashboardPipelineRoute: typeof DashboardPipelineRoute
  DashboardPortfolioRoute: typeof DashboardPortfolioRoute
  DashboardPropostasRoute: typeof DashboardPropostasRoute
  DashboardRelatorioRoute: typeof DashboardRelatorioRoute
  DashboardSelecionarWorkspaceRoute: typeof DashboardSelecionarWorkspaceRoute
  DashboardTemplatesRoute: typeof DashboardTemplatesRoute
  DashboardIndexRoute: typeof DashboardIndexRoute
}

const DashboardRouteRouteChildren: DashboardRouteRouteChildren = {
  DashboardConfiguracoesRoute: DashboardConfiguracoesRoute,
  DashboardFollowupsRoute: DashboardFollowupsRoute,
  DashboardImportarRoute: DashboardImportarRoute,
  DashboardLeadsRoute: DashboardLeadsRoute,
  DashboardPipelineRoute: DashboardPipelineRoute,
  DashboardPortfolioRoute: DashboardPortfolioRoute,
  DashboardPropostasRoute: DashboardPropostasRoute,
  DashboardRelatorioRoute: DashboardRelatorioRoute,
  DashboardSelecionarWorkspaceRoute: DashboardSelecionarWorkspaceRoute,
  DashboardTemplatesRoute: DashboardTemplatesRoute,
  DashboardIndexRoute: DashboardIndexRoute,
}

const DashboardRouteRouteWithChildren = DashboardRouteRoute._addFileChildren(
  DashboardRouteRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  DashboardRouteRoute: DashboardRouteRouteWithChildren,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
